{% set version = "2.5" %}

package:
  name: pagmo
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo2/archive/v{{ version }}.tar.gz
  sha256: b88e1c0468145d97983e648918c988a377e2335a12ea0429be34bdb06dc533fd

build:
  number: 0
  skip: true  # [(win and py<36) or win32]
  features:
    - vc14  # [win and py>=36]

requirements:
  build:
    - python              # [win]
    - vc 14               # [win and py>=36]
    - toolchain
    - cmake
    - eigen
    - nlopt
    - boost-cpp 1.65.1
    - ipopt               # [unix]
  run:
    - vc 14               # [win and py>=36]
    - eigen
    - nlopt
    - boost-cpp 1.65.1
    - ipopt               # [unix]

test:
  commands:
    - test -f $PREFIX/include/pagmo/pagmo.hpp               # [unix]
    - if not exist %LIBRARY_INC%\\pagmo\\pagmo.hpp exit 1   # [win]

about:
  home: https://esa.github.io/pagmo2/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'A C++ / Python platform to perform parallel computations of optimisation tasks (global and local) via the asynchronous generalized island model'

extra:
  recipe-maintainers:
    - bluescarni
    - darioizzo
