{% set version = "2.2" %}

package:
  name: pagmo
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo2/archive/v{{ version }}.tar.gz
  sha256: 5d18c2bb97f7afe36bc6a7ce3bbf9222220676f7710e3767e05d55305d880867

build:
  number: 0
  skip: true  # [(win and py27) or win32]

requirements:
  build:
    - toolchain
    - cmake
    - eigen
    - nlopt
    - boost-cpp 1.63.*
    - ipopt               # [unix]
  run:
    - eigen
    - nlopt
    - boost-cpp 1.63.*
    - ipopt               # [unix]

test:
  commands:
    - test -f $PREFIX/include/pagmo/pagmo.hpp               # [unix]
    - if not exist %LIBRARY_INC%\\pagmo\\pagmo.hpp exit 1   # [win]

about:
  home: https://esa.github.io/pagmo2/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'A C++ / Python platform to perform parallel computations of optimisation tasks (global and local) via the asynchronous generalized island model'

extra:
  recipe-maintainers:
    - bluescarni
    - darioizzo
