{% set version = "2.3" %}

package:
  name: pagmo
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo2/archive/v{{ version }}.tar.gz
  sha256: 22a225801c0f484accfe0edfe6ae0618a460cce0aada6b3b4fc5ee891a2f9e43

build:
  number: 0
  skip: true  # [(win and py<35) or win32]
  features:
    - vc14  # [win and py>=35]

requirements:
  build:
    - python              # [win]
    - vc 14               # [win and py>=35]
    - toolchain
    - cmake
    - eigen
    - nlopt
    - boost-cpp 1.63.*
    - ipopt               # [unix]
  run:
    - vc 14               # [win and py>=35]
    - eigen
    - nlopt
    - boost-cpp 1.63.*
    - ipopt               # [unix]

test:
  commands:
    - test -f $PREFIX/include/pagmo/pagmo.hpp               # [unix]
    - if not exist %LIBRARY_INC%\\pagmo\\pagmo.hpp exit 1   # [win]

about:
  home: https://esa.github.io/pagmo2/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'A C++ / Python platform to perform parallel computations of optimisation tasks (global and local) via the asynchronous generalized island model'

extra:
  recipe-maintainers:
    - bluescarni
    - darioizzo
