{% set version = "2.10" %}

package:
  name: pagmo
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo2/archive/v{{ version }}.tar.gz
  sha256: 2fa95e2b464ddeadb9fc09bd314081293f02a1b6abc11c0b05064729a077227c

build:
  number: 1002
  skip: True  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - eigen
    - nlopt
    - boost-cpp
    - ipopt               # [unix]
  run:
    - eigen
    - nlopt
    - boost-cpp
    - ipopt               # [unix]

test:
  commands:
    - test -f $PREFIX/include/pagmo/pagmo.hpp               # [unix]
    - if not exist %LIBRARY_INC%\\pagmo\\pagmo.hpp exit 1   # [win]

about:
  home: https://esa.github.io/pagmo2/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'A C++ / Python platform to perform parallel computations of optimisation tasks (global and local) via the asynchronous generalized island model'

extra:
  recipe-maintainers:
    - bluescarni
    - darioizzo
