{% set version = "2.11.2" %}

package:
  name: pagmo
  version: {{ version }}

source:
  url: https://github.com/esa/pagmo2/archive/v{{ version }}.tar.gz
  sha256: fb21c515534a11a37372e578b2fd7b389ee8dae0f89a6f4b3dd881a977ad0631

build:
  number: 0
  skip: True  # [win and vc<14]

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - eigen
    - nlopt
    - boost-cpp
    - tbb
    - tbb-devel
    - ipopt               # [unix]
  run:
    - eigen
    - nlopt
    - boost-cpp
    - tbb
    - tbb-devel
    - ipopt               # [unix]

test:
  commands:
    - test -f $PREFIX/include/pagmo/pagmo.hpp               # [unix]
    - if not exist %LIBRARY_INC%\\pagmo\\pagmo.hpp exit 1   # [win]

about:
  home: https://esa.github.io/pagmo2/
  license: GPL v3 and LGPL v3
  license_file: COPYING.lgpl3
  summary: 'A C++ / Python platform to perform parallel computations of optimisation tasks (global and local) via the asynchronous generalized island model'

extra:
  recipe-maintainers:
    - bluescarni
    - darioizzo
