travis:
  secure:
    BINSTAR_TOKEN: 4xrdpwOoSdP8lLCdiaufkzRYl4mIsOoHYwzGVaOAR4ouR9ff9U7U/G4JV1HmCXM3DoQfkowjpiUKP18eM6/mGW8tYDdKIBv2/sdzjV8bLaKw0NvRe8cTEKkV5rm6VJuJx1cKPKrdFnQAjsfxD8SKS4vGFHoiVJw6z2t9d2obwIT8MsozaGI2X7nO+b0ooHz8vRNGBWF5dJ9sBUIMHyvAhViRpauVB9rN02o65JtQb8wAh9oDxg54iBPJ6X/K+3X3XaafXbKzT2lO4LZ09NfckgWJNMV7yJmdO1URgj8QtXPWWQpfDn0BGUr40IaRWSZsxbRiLZOhGEd71mQgw8MFiPheLWI3mO3uvHa2fjKB2/S9eYMarpQxAS51Cf2cjGMjI6kd7jOZVKkBN3tmkkFEcFf2ZuFIUH4bF0v53zpEOhQOvPmyeRvX8VEJ8GNvRYEQVRxLjwX32eAyenJX80XmFG9irasFDRNvX5vrFaFMshmiOBpYxV9opQm8vU2OV88PbZQ+G3A9YOeyQ4onOHA/7MEO/y/TyhGZ56o9+C6J+ae0I2a9BxR995Xgws+9ZADj+yInuXkaSZDhqNxVzJXD0uYUSDXYsQK2L+A/EtuY3+1eZv1KdSzxsdp0ZYiBt7/edSacBThfO5XQTzRKoOu6YHspA4yI5/SyfxGv/BqDC1o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
