travis:
  secure:
    BINSTAR_TOKEN: CN8k7Fd5KBU2Tz24qeFLehXoNglmbWeOGKS14WwM0ClwZVcJgbeNSbZke25rjM0/rTowMYMW4M1Hqv2ocnENcxtMgkT/+PoMhyBYJ8eqL+sjtRKJn0ifGt71PhO/a2jrXrLlk8gJND6owXq03AZ4gMRGJyhS51vYHiOCcvkYbHHxyXJC/wQWSIRwhlmwRbKbCgFph/waD/BHofh+tmoFIJh4+Lc8+1erR7iku7+nDuLPBtlTw2mr/762weQquKcjfG44OZ5mOTFteShZKnwAZW+dsF4qod2Fx1wibCoo2L4oHuRPK45xOFj9C6oOOKanCCEjRERRzXgFFE7M0quhzuxdOKVIr8/X1+EC8lmvN3tefYUMTmBVfqTvBRa6I9h+ykoVDSh3HSVFy/UGHPa2/lNC9GS8zqGSj7tQqE3kiW3PcgEj3En/09AGwTSq9aliK/KJMqQ9Daj+lulUZHARsiOG9tR0quGC5jtKzmsBjyMEOt0DkJh+7PjtCNGMLRAqjdxR+t4y/VffUd4HJUsWHdkaNLJJAzZFtGE6ariDLZfnMercCBCWc6dKuNOrjNw535WdBQjspILUze1Owxzt1QnRQOW7morY3YYl2AvrScEqTBslqcIzudOS1PRCvcmZD/5e420WP4jbToIQba/X7Zl8mHpNDaRtI1SVrl9Tst4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
