travis:
  secure:
    BINSTAR_TOKEN: zXeBIV2CbEa7WriKHEwYzQtnXUKIN/UBTykHOw8KLupggRMvM0QB+xzXAmM4229Jgrivp7kOKgH9m7mJSrrjNJ68UWKw/ERIuNWBcEFCbVzfiqQHFhzVybt+YHkb9GCX1DniyCcoK8CHvGKEviMXw8S0OW3gnVYjLV4DEB1wvGPDQyEQx252dS9p16tG5HflO2dftS8fDznWSr2nWJicy9i8BP8h/iXe4E0jN0dQYLsp6myH0NNSil1X76k9vcEMXdoXVespL2NBgfv/L5EXaOCb/BBb9t//npSHQo3ymjFy0eCArMIgpv0WSP3bmrMEKzzdgDHWwzBTPMl7l3fwOtW0zWITxR8dTnXMuAM2lvtNNkJItu5l+gqdYpoYQyi5ZI0lwMensp9RgJX95elVxNULul07pgjZP5lkqm8yDFJlIDCq5s6EKifF8Q2U2xmXgIRL3RDpzCoIBRHZv9pcChRiLLkU5xCn7nAIIt0mb+9Wr/BOglJFO0jDXEKl5Z7+vOSTQ7Gk4VOUWT21olCuqq6U4yzmniy5mp7msFK/d9BbpOJH394yle4G/3OLrN+xt7xUaHQqSMcy4kcrt6xzrENk8XlLTRMfLxPpeMqWsa1JuF7Hizrue8OQ4qsh2ac1ZzRxYJBmgXuwnDmWyOoKr+WF7rnrLqTkzl05rZHkTyI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
