travis:
  secure:
    BINSTAR_TOKEN: qM+HnZShNccdfrdNuZyKhK4K3N03/7xo/TP3dt9BXJed8MNtRbcMX5K1b2oY3qeoWIZGuFa7zuBRaZxRz4zWXEc12jVpdLAwizzv+YcgUxWa2mA0/qS4VUZGo+jCm+jeno/IYUQMgACur/iwwAyTiBWtA0FEggpl4aoMReW6W/ZjvZdDW2shJ3kq+wJDxWcDz1eGy1sQ9egeLOki7E/d9cn7AZmDqsWqm3xeTP0xpF/brzQBLDfmtRIt4wiCurQYb4YambqB88Y4Dat5/RUMEtbO9+RCcUByf2Ycum7zP+K8dzmz/9D603GnYqRrg2hBnYxW877YZqdsrrzQVWp+pmrPvwKsm784ChilnuT+lhVM58uBRluWZAh0Gn+X2ylaLfTe+Ni1Pc6lmD9cGudRZ/NqkMr4BmUdoVL/xwhjogitSpYgvOLzgCJURndSWz+MbFblf/OYVJmGhukGw2xbWD3dz6iUpk9E2kA+vJeCPdC6OrTJwzbmxwM6LunbHJZ3bE58rdrFgpV0nOlQLwYL0+XMQArljNXgizVfkrUC8u5e7rdEtt/4N2DMUityb9VvUVUv6BXzHqQy8VXDg2hKhx7rnE10KNOGQy/Avfu5qLONLlGw4UUuQDANAdZJLOwL1l0XJdynYnwjjdDIFFXFi7iuuIFHR34Y+5TmeRtG4nw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
